[package]
name = "dns-server"
version = "0.1.0"
edition = "2024"

[features]
default = ["sqlite", "resolver", "rustls-platform-verifier", "recursor", "blocklist"]

ascii-art = []
blocklist = []
recursor = []
# Recursive Resolution is Experimental!
resolver = []
sqlite = []
prometheus-metrics = []
metrics = []
rustls-platform-verifier = []

[dependencies]
async-trait = "0.1"
cfg-if = "1"
clap = { version = "4.0", features = ["std", "derive"] }
hickory-client = { version = "0.25.2" }
hickory-recursor = { version = "0.25.2" }
hickory-resolver = { version = "0.25.2" }
hickory-server = { version = "0.25.2", features = ["resolver", "sqlite", "recursor", "blocklist"] }
hickory-proto = { version = "0.25.2", features = ["std"] }
ipnet = { version = "2.3.0" }
libc = "0.2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
serde = "1.0"
serde_yaml = "0.9"
socket2 = "0.5"
time = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1.30" }
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
